# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui



try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1562, 1001)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.sname = QtGui.QComboBox(self.groupBox)
        self.sname.setObjectName(_fromUtf8("sname"))
        
        # adding Satellites' Names database to Combo Box
        self.sname.setEditable(True)
        for k,v in sorted(satellites.items()):
            self.sname.addItem(_fromUtf8(k))
        
        self.verticalLayout_3.addWidget(self.sname)
        self.stype = QtGui.QLineEdit(self.groupBox)
        self.stype.setObjectName(_fromUtf8("stype"))
        self.verticalLayout_3.addWidget(self.stype)
        self.phaiss = QtGui.QDoubleSpinBox(self.groupBox)
        self.phaiss.setMinimum(-180.0)
        self.phaiss.setMaximum(180.0)
        self.phaiss.setObjectName(_fromUtf8("phaiss"))
        self.verticalLayout_3.addWidget(self.phaiss)
        self.lineEdit_16 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.verticalLayout_3.addWidget(self.lineEdit_16)
        self.lineEdit_17 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.verticalLayout_3.addWidget(self.lineEdit_17)
        self.lineEdit_18 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.verticalLayout_3.addWidget(self.lineEdit_18)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_12.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_12.addWidget(self.label_14)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.phaibs = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.phaibs.setMinimum(-180.0)
        self.phaibs.setMaximum(180.0)
        self.phaibs.setObjectName(_fromUtf8("phaibs"))
        self.verticalLayout_11.addWidget(self.phaibs)
        self.lbs = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.lbs.setMinimum(-90.0)
        self.lbs.setMaximum(90.0)
        self.lbs.setObjectName(_fromUtf8("lbs"))
        self.verticalLayout_11.addWidget(self.lbs)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.calc = QtGui.QPushButton(self.splitter)
        self.calc.setObjectName(_fromUtf8("calc"))
        self.groupBox_3 = QtGui.QGroupBox(self.splitter_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.webView = QtWebKit.QWebView(self.groupBox_3)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("file:///C:/Users/EngSh/Desktop/satellite_project/final/map.html")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.gridLayout_4.addWidget(self.webView, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter_3 = QtGui.QSplitter(self.groupBox_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.widget1 = QtGui.QWidget(self.splitter_3)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_21 = QtGui.QLabel(self.widget1)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_5.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.widget1)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_5.addWidget(self.label_22)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_5)
        self.label_23 = QtGui.QLabel(self.widget1)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_12.addWidget(self.label_23)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_24 = QtGui.QLabel(self.widget1)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_8.addWidget(self.label_24)
        self.label_25 = QtGui.QLabel(self.widget1)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_8.addWidget(self.label_25)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_8)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.Azlabel = QtGui.QLabel(self.widget1)
        self.Azlabel.setFrameShape(QtGui.QFrame.Box)
        self.Azlabel.setFrameShadow(QtGui.QFrame.Plain)
        self.Azlabel.setObjectName(_fromUtf8("Azlabel"))
        self.horizontalLayout_9.addWidget(self.Azlabel)
        self.Ellabel = QtGui.QLabel(self.widget1)
        self.Ellabel.setFrameShape(QtGui.QFrame.Box)
        self.Ellabel.setObjectName(_fromUtf8("Ellabel"))
        self.horizontalLayout_9.addWidget(self.Ellabel)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_9)
        self.Declabel = QtGui.QLabel(self.widget1)
        self.Declabel.setFrameShape(QtGui.QFrame.Box)
        self.Declabel.setObjectName(_fromUtf8("Declabel"))
        self.horizontalLayout_11.addWidget(self.Declabel)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.Dlabel = QtGui.QLabel(self.widget1)
        self.Dlabel.setFrameShape(QtGui.QFrame.Box)
        self.Dlabel.setObjectName(_fromUtf8("Dlabel"))
        self.horizontalLayout_10.addWidget(self.Dlabel)
        self.Rlabel = QtGui.QLabel(self.widget1)
        self.Rlabel.setFrameShape(QtGui.QFrame.Box)
        self.Rlabel.setObjectName(_fromUtf8("Rlabel"))
        self.horizontalLayout_10.addWidget(self.Rlabel)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.gridLayout_2.addWidget(self.splitter_3, 1, 0, 2, 2)
        self.gridLayout_3.addWidget(self.groupBox_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1562, 38))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.calc.clicked.connect(self.calculations)
        self.sname.currentIndexChanged.connect(self.combo)
        

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Satellite (BETA 0.1)", None))
        self.groupBox.setTitle(_translate("MainWindow", "Satellite\'s Information", None))
        self.label.setText(_translate("MainWindow", "Name", None))
        self.label_2.setText(_translate("MainWindow", "Type", None))
        self.label_3.setText(_translate("MainWindow", "Longitude", None))
        self.label_4.setText(_translate("MainWindow", "Frequency", None))
        self.label_5.setText(_translate("MainWindow", "Dish Size", None))
        self.label_6.setText(_translate("MainWindow", "Parameter", None))
        self.stype.setPlaceholderText(_translate("MainWindow", "Enter Satellite\'s Type", None))
        self.lineEdit_16.setPlaceholderText(_translate("MainWindow", "Enter Operating Frequency", None))
        self.lineEdit_17.setPlaceholderText(_translate("MainWindow", "Enter Antenna Dish Size", None))
        self.lineEdit_18.setPlaceholderText(_translate("MainWindow", "Enter Orbital parameter", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "User\'s Information", None))
        self.label_13.setText(_translate("MainWindow", "User\'s Longitude", None))
        self.label_14.setText(_translate("MainWindow", "User\'s Latitude", None))
        self.calc.setText(_translate("MainWindow", "Calculate", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Google Map", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Output", None))
        self.label_21.setText(_translate("MainWindow", "Azimuth", None))
        self.label_22.setText(_translate("MainWindow", "Elevation", None))
        self.label_23.setText(_translate("MainWindow", "Declination Angle", None))
        self.label_24.setText(_translate("MainWindow", "Distance", None))
        self.label_25.setText(_translate("MainWindow", "Round Trip", None))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

